use fractic_server_error::{CriticalError, ServerError};

use crate::{
    errors::DynamoInvalidParent,
    schema::{DynamoObject, IdLogic, PkSk},
};

use super::{id_path::RawIdPath, placement::place_for, relations::validate_parent_relation};

const ID_VALUE_WIDTH: usize = 16;
const MAX_TIMESTAMP_ID: i64 = 9_999_999_999_999_999;
const BASE62_ALPHABET: &[u8; 62] =
    b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

/// Controls deterministic ID generation used by batch operations and tests.
#[derive(Default)]
pub(crate) struct IdGenerationOptions {
    pub timestamp_millis: Option<i64>,
}

/// Generates a logical ID for a new object.
pub(crate) fn generate_id<T: DynamoObject>(
    data: &T::Data,
    parent: &PkSk,
) -> Result<PkSk, ServerError> {
    generate_id_with_options::<T>(data, parent, IdGenerationOptions::default())
}

/// Generates a logical ID, optionally using a caller-supplied timestamp.
pub(crate) fn generate_id_with_options<T: DynamoObject>(
    data: &T::Data,
    parent: &PkSk,
    options: IdGenerationOptions,
) -> Result<PkSk, ServerError> {
    validate_parent_relation::<T>(parent)
        .map_err(|error| DynamoInvalidParent::new(&error.to_string()))?;
    validate_configured_label(T::id_label())?;

    let terminal_segment =
        match T::id_logic() {
            IdLogic::Phantom => return Err(CriticalError::new(
                "IDs for IdLogic::Phantom must be constructed manually; phantom objects cannot be \
                 persisted",
            )),
            IdLogic::Uuid => format!("{}#{}", T::id_label(), new_uuid_value()),
            IdLogic::Timestamp => {
                let timestamp = options
                    .timestamp_millis
                    .unwrap_or_else(|| chrono::Utc::now().timestamp_millis());
                format!("{}#{}", T::id_label(), timestamp_value(timestamp)?)
            }
            IdLogic::Singleton | IdLogic::SingletonExt => format!("@{}", T::id_label()),
            IdLogic::IndexedSingleton(key) | IdLogic::IndexedSingletonExt(key) => {
                format!("@{}[{}]", T::id_label(), key(data))
            }
            IdLogic::BatchOptimized { .. } => {
                return Err(CriticalError::new(
                    "IDs for IdLogic::BatchOptimized are generated by \
                 DynamoUtil::batch_replace_all_ordered; regular ID generation was unexpectedly \
                 requested",
                ))
            }
        };

    Ok(place_for::<T>(parent, &terminal_segment))
}

/// Regenerates the terminal segment value of a UUID ID.
pub(crate) fn regenerate_uuid(sk: &str) -> Result<String, ServerError> {
    Ok(RawIdPath::new(sk)
        .parse()?
        .with_terminal_segment_value(&new_uuid_value()))
}

/// Regenerates the terminal segment value of a timestamp ID.
pub(crate) fn regenerate_timestamp(sk: &str, timestamp_millis: i64) -> Result<String, ServerError> {
    Ok(RawIdPath::new(sk)
        .parse()?
        .with_terminal_segment_value(&timestamp_value(timestamp_millis)?))
}

fn validate_configured_label(label: &str) -> Result<(), ServerError> {
    if label.is_empty() || label.contains(['#', '@', '[', ']', '+']) {
        return Err(CriticalError::with_debug(
            "DynamoObject::id_label() must be non-empty and cannot contain `#`, `@`, `[`, `]`, or \
             `+`",
            &label,
        ));
    }
    Ok(())
}

fn base62_encode(mut value: u128, width: usize) -> String {
    let mut result = vec!['0'; width];
    for position in (0..width).rev() {
        result[position] = BASE62_ALPHABET[(value % 62) as usize] as char;
        value /= 62;
    }
    result.into_iter().collect()
}

fn new_uuid_value() -> String {
    base62_encode(uuid::Uuid::new_v4().as_u128(), ID_VALUE_WIDTH)
}

fn timestamp_value(timestamp_millis: i64) -> Result<String, ServerError> {
    if !(0..=MAX_TIMESTAMP_ID).contains(&timestamp_millis) {
        return Err(CriticalError::with_debug(
            "timestamp ID must be a non-negative value that fits in 16 decimal digits",
            &timestamp_millis,
        ));
    }
    Ok(format!("{timestamp_millis:0ID_VALUE_WIDTH$}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_fixed_width_base62_values() {
        let encoded = base62_encode(1_234_567_890, ID_VALUE_WIDTH);
        assert_eq!(encoded.len(), ID_VALUE_WIDTH);
        assert!(encoded
            .chars()
            .all(|character| BASE62_ALPHABET.contains(&(character as u8))));

        let uuid = new_uuid_value();
        assert_eq!(uuid.len(), ID_VALUE_WIDTH);
        assert!(uuid
            .chars()
            .all(|character| BASE62_ALPHABET.contains(&(character as u8))));
    }

    #[test]
    fn formats_and_bounds_timestamp_values() {
        assert_eq!(timestamp_value(1_234).unwrap(), "0000000000001234");
        assert!(timestamp_value(-1).is_err());
        assert!(timestamp_value(MAX_TIMESTAMP_ID + 1).is_err());
    }
}
