use fractic_server_error::{CriticalError, ServerError};

use crate::{
    errors::{DynamoInvalidOperation, DynamoInvalidParent},
    schema::{DynamoObject, IdLogic, PkSk},
};

use super::{
    id_path::RawIdPath, placement::place_terminal_segment, relations::validate_parent_relation,
};

const ID_VALUE_WIDTH: usize = 22;
const MAX_UUID_V7_TIMESTAMP_MILLIS: i64 = (1_i64 << 48) - 1;
const BASE62_ALPHABET: &[u8; 62] =
    b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct Base62Uuid([u8; ID_VALUE_WIDTH]);

impl Base62Uuid {
    fn encode(uuid: uuid::Uuid) -> Self {
        let mut value = uuid.as_u128();
        let mut encoded = [b'0'; ID_VALUE_WIDTH];
        for position in (0..ID_VALUE_WIDTH).rev() {
            encoded[position] = BASE62_ALPHABET[(value % 62) as usize];
            value /= 62;
        }
        debug_assert_eq!(value, 0, "22 base62 characters can encode every UUID");
        Self(encoded)
    }

    fn as_str(&self) -> &str {
        std::str::from_utf8(&self.0).expect("the base62 alphabet is valid UTF-8")
    }
}

impl std::fmt::Display for Base62Uuid {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// Generates a logical ID for a new object.
pub(crate) fn generate_id<T: DynamoObject>(
    data: &T::Data,
    parent: &PkSk,
) -> Result<PkSk, ServerError> {
    validate_parent_relation::<T>(parent)
        .map_err(|error| DynamoInvalidParent::new(&error.to_string()))?;
    validate_configured_label(T::id_label())?;

    let terminal_segment = match T::id_logic() {
        IdLogic::Phantom => {
            return Err(CriticalError::new(concat!(
                "IDs for IdLogic::Phantom must be constructed manually; ",
                "phantom objects cannot be persisted",
            )))
        }
        IdLogic::UuidV4 => format!("{}#{}", T::id_label(), new_uuid_v4_value()),
        IdLogic::UuidV7 => format!("{}#{}", T::id_label(), new_uuid_v7_value()),
        IdLogic::Singleton | IdLogic::SingletonExt => format!("@{}", T::id_label()),
        IdLogic::IndexedSingleton(key) | IdLogic::IndexedSingletonExt(key) => {
            format!("@{}[{}]", T::id_label(), key(data))
        }
        IdLogic::BatchOptimized { .. } => {
            return Err(CriticalError::new(concat!(
                "IDs for IdLogic::BatchOptimized are generated by ",
                "DynamoUtil::batch_replace_all_ordered; regular ID generation was unexpectedly ",
                "requested",
            )))
        }
    };

    Ok(place_terminal_segment::<T>(parent, &terminal_segment))
}

/// Constructs the first possible UUID-v7 ID at `timestamp_millis`.
pub(crate) fn uuid_v7_lower_bound<T: DynamoObject>(
    parent: &PkSk,
    timestamp_millis: i64,
) -> Result<PkSk, ServerError> {
    uuid_v7_bound::<T>(parent, timestamp_millis, false)
}

/// Constructs the last possible UUID-v7 ID at `timestamp_millis`.
pub(crate) fn uuid_v7_upper_bound<T: DynamoObject>(
    parent: &PkSk,
    timestamp_millis: i64,
) -> Result<PkSk, ServerError> {
    uuid_v7_bound::<T>(parent, timestamp_millis, true)
}

/// Regenerates the terminal segment value of a UUID-v4 ID.
pub(crate) fn regenerate_uuid_v4(sk: &str) -> Result<String, ServerError> {
    let value = new_uuid_v4_value();
    Ok(RawIdPath::new(sk)
        .parse()?
        .with_terminal_segment_value(value.as_str()))
}

/// Regenerates the terminal segment value of a UUID-v7 ID.
pub(crate) fn regenerate_uuid_v7(sk: &str) -> Result<String, ServerError> {
    let value = new_uuid_v7_value();
    Ok(RawIdPath::new(sk)
        .parse()?
        .with_terminal_segment_value(value.as_str()))
}

fn uuid_v7_bound<T: DynamoObject>(
    parent: &PkSk,
    timestamp_millis: i64,
    upper: bool,
) -> Result<PkSk, ServerError> {
    if !matches!(T::id_logic(), IdLogic::UuidV7) {
        return Err(DynamoInvalidOperation::new(&format!(
            "UUID-v7 bounds require IdLogic::UuidV7, but object type '{}' uses different ID logic",
            T::id_label()
        )));
    }
    validate_parent_relation::<T>(parent)
        .map_err(|error| DynamoInvalidParent::new(&error.to_string()))?;
    validate_configured_label(T::id_label())?;

    let terminal_segment = format!(
        "{}#{}",
        T::id_label(),
        uuid_v7_bound_value(timestamp_millis, upper)?
    );
    Ok(place_terminal_segment::<T>(parent, &terminal_segment))
}

fn validate_configured_label(label: &str) -> Result<(), ServerError> {
    if label.is_empty() || label.contains(['#', '@', '[', ']', '+']) {
        return Err(CriticalError::with_debug(
            "DynamoObject::id_label() must be non-empty and cannot contain `#`, `@`, `[`, `]`, or \
             `+`",
            &label,
        ));
    }
    Ok(())
}

fn new_uuid_v4_value() -> Base62Uuid {
    Base62Uuid::encode(uuid::Uuid::new_v4())
}

fn new_uuid_v7_value() -> Base62Uuid {
    Base62Uuid::encode(uuid::Uuid::now_v7())
}

#[cfg(test)]
fn uuid_v7_value_at(timestamp_millis: i64) -> Result<Base62Uuid, ServerError> {
    let timestamp_millis = validate_timestamp_millis(timestamp_millis)?;
    let timestamp = uuid::Timestamp::from_unix_time(
        timestamp_millis / 1_000,
        ((timestamp_millis % 1_000) * 1_000_000) as u32,
        0,
        0,
    );
    Ok(Base62Uuid::encode(uuid::Uuid::new_v7(timestamp)))
}

fn uuid_v7_bound_value(timestamp_millis: i64, upper: bool) -> Result<Base62Uuid, ServerError> {
    let timestamp_millis = validate_timestamp_millis(timestamp_millis)? as u128;
    let mut value = timestamp_millis << 80;
    value |= 0x7_u128 << 76;
    value |= 0b10_u128 << 62;
    if upper {
        value |= 0xfff_u128 << 64;
        value |= (1_u128 << 62) - 1;
    }
    Ok(Base62Uuid::encode(uuid::Uuid::from_u128(value)))
}

pub(crate) fn uuid_v7_value_lower_bound(timestamp_millis: i64) -> Result<String, ServerError> {
    Ok(uuid_v7_bound_value(timestamp_millis, false)?.to_string())
}

pub(crate) fn uuid_v7_value_upper_bound(timestamp_millis: i64) -> Result<String, ServerError> {
    Ok(uuid_v7_bound_value(timestamp_millis, true)?.to_string())
}

fn validate_timestamp_millis(timestamp_millis: i64) -> Result<u64, ServerError> {
    if !(0..=MAX_UUID_V7_TIMESTAMP_MILLIS).contains(&timestamp_millis) {
        return Err(DynamoInvalidOperation::with_debug(
            "UUID-v7 timestamp must be a non-negative Unix epoch millisecond that fits in 48 bits",
            &timestamp_millis,
        ));
    }
    Ok(timestamp_millis as u64)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn decode_base62(value: &str) -> u128 {
        value.bytes().fold(0_u128, |decoded, byte| {
            let digit = BASE62_ALPHABET
                .iter()
                .position(|candidate| *candidate == byte)
                .unwrap() as u128;
            decoded * 62 + digit
        })
    }

    #[test]
    fn base62_encoding_is_fixed_width_and_lossless() {
        let encoded = Base62Uuid::encode(uuid::Uuid::from_u128(u128::MAX));
        assert_eq!(encoded.as_str().len(), ID_VALUE_WIDTH);
        assert_eq!(decode_base62(encoded.as_str()), u128::MAX);
        assert!(encoded
            .as_str()
            .chars()
            .all(|character| BASE62_ALPHABET.contains(&(character as u8))));

        let uuid = new_uuid_v4_value();
        assert_eq!(uuid.as_str().len(), ID_VALUE_WIDTH);
        assert!(uuid
            .as_str()
            .chars()
            .all(|character| BASE62_ALPHABET.contains(&(character as u8))));
    }

    #[test]
    fn generates_uuid_v4_and_v7_values() {
        let uuid = uuid::Uuid::from_u128(decode_base62(new_uuid_v4_value().as_str()));
        assert_eq!(uuid.get_version_num(), 4);

        let timestamp_value = uuid_v7_value_at(1_234).unwrap();
        let timestamp = uuid::Uuid::from_u128(decode_base62(timestamp_value.as_str()));
        assert_eq!(timestamp.get_version_num(), 7);
        assert_eq!(
            timestamp.get_timestamp().unwrap().to_unix(),
            (1, 234_000_000)
        );
    }

    #[test]
    fn uuid_v7_bounds_enclose_every_uuid_at_the_millisecond() {
        let timestamp_millis = 1_234;
        let lower = uuid_v7_bound_value(timestamp_millis, false).unwrap();
        let value = uuid_v7_value_at(timestamp_millis).unwrap();
        let upper = uuid_v7_bound_value(timestamp_millis, true).unwrap();

        assert!(lower.as_str() <= value.as_str());
        assert!(value.as_str() <= upper.as_str());
        assert!(uuid_v7_bound_value(-1, false).is_err());
        assert!(uuid_v7_bound_value(MAX_UUID_V7_TIMESTAMP_MILLIS + 1, true).is_err());
    }
}
